/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mobilescotter;

/**
 *
 * @author mustafasamil.ileri
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbl_password = new javax.swing.JLabel();
        jbl_username = new javax.swing.JLabel();
        username_label = new javax.swing.JTextField();
        btn_signin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_signup = new javax.swing.JButton();
        password_jpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbl_password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbl_password.setText("Password :");
        jPanel1.add(jbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 317, 104, -1));

        jbl_username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbl_username.setText("Username :");
        jPanel1.add(jbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 256, -1, -1));
        jPanel1.add(username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 120, 40));

        btn_signin.setBackground(new java.awt.Color(255, 255, 255));
        btn_signin.setIcon(new javax.swing.ImageIcon("C:\\Users\\mustafasamil.ileri\\Desktop\\Java\\JAVA\\MobileScotter\\icon\\icons8-sign-in-48 (1).png")); // NOI18N
        btn_signin.setText("Sign In");
        btn_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signinActionPerformed(evt);
            }
        });
        jPanel1.add(btn_signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 130, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\mustafasamil.ileri\\Desktop\\Java\\JAVA\\MobileScotter\\icon\\output-onlinepngtools.png")); // NOI18N
        jLabel3.setName(""); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, 278, 212));

        btn_signup.setIcon(new javax.swing.ImageIcon("C:\\Users\\mustafasamil.ileri\\Desktop\\Java\\JAVA\\MobileScotter\\icon\\icons8-sign-up-48.png")); // NOI18N
        btn_signup.setText("Sign Up");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        jPanel1.add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 130, 50));

        password_jpass.setText("jPasswordField1");
        jPanel1.add(password_jpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signinActionPerformed
        // TODO add your handling code here:
        String user_name=username_label.getText();
        String password=password_jpass.getText();
        
        System.out.println("kullancı: "+user_name);
        System.out.println();
              
        
        
             
    }//GEN-LAST:event_btn_signinActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_signupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_signin;
    private javax.swing.JButton btn_signup;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jbl_password;
    private javax.swing.JLabel jbl_username;
    private javax.swing.JPasswordField password_jpass;
    private javax.swing.JTextField username_label;
    // End of variables declaration//GEN-END:variables
}
